// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHEiYDJzVkhSf_mdfSUfbf32jv0T7SXnA',
    appId: '1:952601771173:android:f7644bc01fbf4db37b214c',
    messagingSenderId: '952601771173',
    projectId: 'quiz-app-c44db',
    storageBucket: 'quiz-app-c44db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEHol-uqfubeDex8qH5j4qGO_d4W02TfA',
    appId: '1:952601771173:ios:9180a4f4709992a57b214c',
    messagingSenderId: '952601771173',
    projectId: 'quiz-app-c44db',
    storageBucket: 'quiz-app-c44db.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0JiphIAAreQNFj8i-wn98OT06jdyUvB4',
    appId: '1:952601771173:web:d59c40281032a9267b214c',
    messagingSenderId: '952601771173',
    projectId: 'quiz-app-c44db',
    authDomain: 'quiz-app-c44db.firebaseapp.com',
    storageBucket: 'quiz-app-c44db.firebasestorage.app',
    measurementId: 'G-89K5FEN4VE',
  );
}
